services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env 
    volumes:
      - ${PWD}/downloads:/app/downloads
      - ${PWD}/cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 120s
