services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M 