services:
  web:
    image: ghcr.io/bdamokos/brussels_transit:stable
    ports:
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:8005:8000" 
      - "0.0.0.0:8085:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PROJECT_ROOT=/app
      - CACHE_DIR=/app/cache
      - DOWNLOADS_DIR=/app/downloads
      - LOGS_DIR=/app/logs
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${PWD:-.}/downloads
        target: /app/downloads
      - type: bind
        source: ${PWD:-.}/cache
        target: /app/cache
      - type: bind
        source: ${PWD:-.}/logs
        target: /app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 120s
      retries: 5
      start_period: 120s