services:
  web:
    build: .
    ports:
      - "0.0.0.0:5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M 