services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5001:5001"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http web:5001
    depends_on:
      web:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M 