#ifndef GTFS_PRECACHE_VERSION_H
#define GTFS_PRECACHE_VERSION_H

#define GTFS_PRECACHE_VERSION_MAJOR 1
#define GTFS_PRECACHE_VERSION_MINOR 0
#define GTFS_PRECACHE_VERSION_PATCH 1

#define GTFS_PRECACHE_VERSION_STRING "1.0.1"

#endif // GTFS_PRECACHE_VERSION_H 